
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8.
import tkinter as tk
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from tkinter import ttk
from tkcalendar import DateEntry


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x700")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 700,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    396.0,
    441.0,
    763.0,
    603.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    771.0,
    441.0,
    1010.0,
    603.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    1018.0,
    441.0,
    1222.0,
    603.0,
    fill="#FFFFFF",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    872.0,
    23.0,
    image=image_image_1
)

canvas.create_text(
    1113.0,
    7.0,
    anchor="nw",
    text="06-08-2023",
    fill="#000000",
    font=("Poppins Regular", 18 * -1)
)

canvas.create_text(
    1050.0,
    7.0,
    anchor="nw",
    text="Date:",
    fill="#000000",
    font=("Poppins SemiBold", 18 * -1)
)

canvas.create_rectangle(
    0.0,
    1.0,
    336.0,
    702.0,
    fill="#000000",
    outline="")

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    157.0,
    115.0,
    image=image_image_2
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=0.0,
    y=230.0,
    width=336.0,
    height=60.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=0.0,
    y=290.0,
    width=336.0,
    height=60.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=0.0,
    y=350.0,
    width=336.0,
    height=60.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=1.0,
    y=410.0,
    width=335.0,
    height=60.0
)

canvas.create_text(
    395.0,
    64.0,
    anchor="nw",
    text="Inventory",
    fill="#8AC926",
    font=("Poppins Bold", 25 * -1)
)

canvas.create_rectangle(
    393.0,
    110.0,
    1222.0,
    112.0,
    fill="#030302",
    outline="")

canvas.create_rectangle(
    395.0,
    398.0,
    1222.0,
    433.0,
    fill="#000000",
    outline="")

canvas.create_text(
    415.0,
    405.0,
    anchor="nw",
    text="Ingredient",
    fill="#FFFFFF",
    font=("Poppins SemiBold", 14 * -1)
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=395.0,
    y=611.0,
    width=266.0,
    height=55.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=675.0,
    y=611.0,
    width=267.0,
    height=55.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=956.0,
    y=611.0,
    width=266.0,
    height=55.0
)

canvas.create_text(
    535.0,
    459.0,
    anchor="nw",
    text="INGREDIENT",
    fill="#030302",
    font=("Poppins SemiBold", 14 * -1)
)

canvas.create_text(
    853.0,
    459.0,
    anchor="nw",
    text="QUANTITY",
    fill="#030302",
    font=("Poppins SemiBold", 14 * -1)
)

canvas.create_text(
    1077.0,
    459.0,
    anchor="nw",
    text="EXPIRATION",
    fill="#030302",
    font=("Poppins SemiBold", 14 * -1)
)

canvas.create_text(
    415.0,
    499.0,
    anchor="nw",
    text="Name:",
    fill="#030302",
    font=("Poppins SemiBold", 14 * -1)
)

canvas.create_text(
    415.0,
    548.0,
    anchor="nw",
    text="Type:",
    fill="#030302",
    font=("Poppins SemiBold", 14 * -1)
)

canvas.create_text(
    791.0,
    494.0,
    anchor="nw",
    text="Kg/s:",
    fill="#030302",
    font=("Poppins SemiBold", 14 * -1)
)

canvas.create_text(
    791.0,
    543.0,
    anchor="nw",
    text="Pc/s:",
    fill="#030302",
    font=("Poppins SemiBold", 14 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    627.0,
    509.0,
    image=image_image_3
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    627.0,
    509.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=524.0,
    y=500.0,
    width=206.0,
    height=17.0
)


button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat"
)
button_8.place(
    x=595.0,
    y=543.0,
    width=28.0,
    height=30.0
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    906.0,
    558.0,
    image=image_image_5
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    906.0,
    558.5,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=854.0,
    y=549.0,
    width=104.0,
    height=17.0
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    906.0,
    509.0,
    image=image_image_6
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    906.0,
    509.5,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=854.0,
    y=500.0,
    width=104.0,
    height=17.0
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    906.0,
    509.5,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=854.0,
    y=500.0,
    width=104.0,
    height=17.0
)

canvas.create_text(
    395.0,
    142.0,
    anchor="nw",
    text="Search:",
    fill="#030302",
    font=("Poppins SemiBold", 14 * -1)
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    639.0,
    152.0,
    image=image_image_7
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    639.5,
    152.5,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=474.0,
    y=143.0,
    width=331.0,
    height=17.0
)

canvas.create_text(
    848.0,
    142.0,
    anchor="nw",
    text="Sort by:",
    fill="#000000",
    font=("Poppins SemiBold", 14 * -1)
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    989.0,
    151.0,
    image=image_image_8
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_9 clicked"),
    relief="flat"
)
button_9.place(
    x=1032.0,
    y=139.0,
    width=24.0,
    height=25.0
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    1149.0,
    152.0,
    image=image_image_9
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_10 clicked"),
    relief="flat"
)
button_10.place(
    x=1190.0,
    y=139.0,
    width=24.0,
    height=25.0
)

button_image_11 = PhotoImage(
    file=relative_to_assets("button_11.png"))
button_11 = Button(
    image=button_image_11,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_11 clicked"),
    relief="flat"
)
button_11.place(
    x=1020.0,
    y=53.0,
    width=200.0,
    height=39.0
)

#########################################################################
# CUSTOM CODE

# CALENDAR
cal=DateEntry(selectmode='day')
cal.grid(row=1, column=1, padx=15)
cal.place(
    x=1050,
    y=490
)

# DROPDOWN MENU

#function to get value of combo box
def cbx_type_click(event):
    global type
    type = cbx_type.get()
    print(type)


# TYPE
cbx_type_options = ["Beef", "Bread", "Chicken", "Juice", "Milk", "Pork", "Potato"]       # change me
cbx_type  = ttk.Combobox(values=cbx_type_options)
cbx_type.bind("<<ComboboxSelected>>", cbx_type_click)
cbx_type.place(
x=513.0,
y=540.0,
width=200,
height=43,
)
cbx_type.config(
font=("Inter ExtraLight", 20 * -1),
justify="center",
state="readonly"
)

window.resizable(False, False)
window.mainloop()
